version: '3'

services:
  mongodb_test:
    image: mongo
    ports: 
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${mongodb_test_username}
      - MONGO_INITDB_ROOT_PASSWORD=${mongodb_test_password}